version: 2
updates:
  # frontend
  - package-ecosystem: "bun"
    directory: "frontend/"
    schedule:
      interval: "weekly"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  # cloud functions
  - package-ecosystem: "bun" # lfg wagmi
    directory: "frontend/functions/"
    schedule:
      interval: "weekly"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  # backend quart
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "weekly"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  # titanic rust service
  - package-ecosystem: "cargo"
    directory: "titanic/"
    schedule:
      interval: "weekly"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  # backend docker
  - package-ecosystem: "docker"
    directory: "backend/"
    schedule:
      interval: "weekly"
