services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/admin-sdk-cred
    secrets:
      - admin-sdk-cred
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      flask:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

secrets:
  admin-sdk-cred:
    file: ./admin-sdk-cred.json
