services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./videos:/app/videos
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/admin-sdk-cred
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    secrets:
      - admin-sdk-cred
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      flask:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60  # Check every minute
      - WATCHTOWER_CLEANUP=true       # Remove old images
      - WATCHTOWER_LABEL_ENABLE=true  # Only watch containers with watchtower.enable=true
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

secrets:
  admin-sdk-cred:
    file: ./admin-sdk-cred.json
