services:
  flask:
    image: ghcr.io/onkr0d/titanic:latest
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/admin-sdk-cred
    secrets:
      - admin-sdk-cred
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: ghcr.io/onkr0d/titanic/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      flask:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

secrets:
  admin-sdk-cred:
    file: ./admin-sdk-cred.json