bind = ["0.0.0.0:5000"]
quic_bind = ["0.0.0.0:5000"]
wsgi_max_body_size = 10737418240 # 10 gigs in bytes
keep_alive_timeout = 5  # Close idle connections after 5s to prevent blocking
worker_class = "asyncio"  # Ensure async worker for better concurrency