services:
  app_proxy:
    environment:
      APP_HOST: titanic_app_1
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"
      APP_PORT: 3029

  app:
    # MUST pin to specific sha256 as per Umbrel requirements
    image: ghcr.io/onkr0d/titanic/titanic:main@sha256:fb3edd22ff4a259ffad02fc3842fdda08adc93e36b7506d76241fe6ccea04350
    # user: "1001:1001"  # Temporarily disabled for debugging
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - BIND_ADDRESS=0.0.0.0:3029
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-titanic-uploader}
      - PLEX_MEDIA_PATH=${PLEX_MEDIA_PATH:-/downloads}
      - IS_DEV=${IS_DEV:-false}
      - RUST_LOG=debug
    volumes:
      - ${APP_DATA_DIR}/downloads:/downloads
