services:
  app:
    # MUST pin to specific sha256 as per Umbrel requirements
    image: ghcr.io/onkr0d/titanic/titanic:main@sha256:d8b309543995e3645f8794e7c1b4cc4b0353d931ec4fca5a8300b4ec771d888b
    ports:
      - "0.0.0.0:3029:3029"
    environment:
      - BIND_ADDRESS=0.0.0.0:3029
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-titanic-uploader}
      - PLEX_MEDIA_PATH=${PLEX_MEDIA_PATH:-/downloads}
      - IS_DEV=${IS_DEV:-false}
      - RUST_LOG=debug
    volumes:
      - ${APP_DATA_DIR}/downloads:/downloads
    restart: on-failure
