services:
  app:
    # MUST pin to specific sha256 as per Umbrel requirements
    image: ghcr.io/onkr0d/titanic/titanic:main@sha256:589440a4207d2665d2fa48dc5c89ffa32061b963bf92457aceb17d10c00467a1
    # user: "1001:1001"  # Temporarily disabled for debugging
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3029:3029
    environment:
      - BIND_ADDRESS=0.0.0.0:3029
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-probably not critical}
      - PLEX_MEDIA_PATH=${PLEX_MEDIA_PATH:-/downloads}
      - IS_DEV=${IS_DEV:-false}
      - RUST_LOG=debug
    volumes:
      - ${APP_DATA_DIR}/downloads:/downloads

  app_proxy:
    image: ghcr.io/getumbrel/umbrel-apps/app-proxy:latest
    environment:
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"
    restart: unless-stopped
    depends_on:
      - app