name: Deploy Functions
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/functions/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/functions
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun install --frozen-lockfile
          bun run build
      - uses: jsryudev/deploy-firebase-functions@v18.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: titanic-uploader
          FUNCTIONS_DIR: frontend/functions
