name: Publish Titanic Umbrel Image

on:
  push:
    branches: ['main']
    paths:
      - 'umbrel-titanic/**'
      - '.github/workflows/publish-umbrel-titanic.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: onkr0d/titanic

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Umbrel
        id: umbrel-meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/umbrel-titanic

      - name: Build and push Umbrel image
        uses: docker/build-push-action@v6.17.0
        with:
          context: ./umbrel-titanic
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.umbrel-meta.outputs.tags }}
          labels: ${{ steps.umbrel-meta.outputs.labels }} 