name: Publish Titanic Umbrel Image

on:
  push:
    branches: ['main']
    paths:
      - 'titanic/**'
      - '.github/workflows/publish-umbrel-titanic.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: onkr0d/titanic

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Umbrel
        id: titanic-meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/titanic

      - name: Build and push Umbrel image (${{ matrix.platform }})
        uses: docker/build-push-action@v6.17.0
        with:
          context: ./titanic
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/titanic:latest
            ${{ steps.titanic-meta.outputs.tags }}
          labels: ${{ steps.titanic-meta.outputs.labels }}
          cache-from: type=gha,scope=titanic-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=titanic-${{ matrix.platform }}